name = "jhoy" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"

[vars]
# UUID = "56255e59-f853-4dc7-ba92-7896ed190767"
# PROXYIP = "103.133.223.50"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "d6a8b2872ad8ddfdecf94701b69147a7"
# API_HOST = "VFiIZgHyoBtPBojOk7kC_UAe43Z8s6YlZGYuGdXC"
